In [1]:

arr = [ 11, 22, 33, 44, 55, 66, 77, 88, 99]


In [75]:
# DAY 1 : Data 
# https://drive.google.com/drive/folders/1UZE8gORol3NcRuViuYZV-ZDWUtSMKzKc

In [2]:
arr


[11, 22, 33, 44, 55, 66, 77, 88, 99]

In [3]:
arr*10

[11,
 22,
 33,
 44,
 55,
 66,
 77,
 88,
 99,
 11,
 22,
 33,
 44,
 55,
 66,
 77,
 88,
 99,
 11,
 22,
 33,
 44,
 55,
 66,
 77,
 88,
 99,
 11,
 22,
 33,
 44,
 55,
 66,
 77,
 88,
 99,
 11,
 22,
 33,
 44,
 55,
 66,
 77,
 88,
 99,
 11,
 22,
 33,
 44,
 55,
 66,
 77,
 88,
 99,
 11,
 22,
 33,
 44,
 55,
 66,
 77,
 88,
 99,
 11,
 22,
 33,
 44,
 55,
 66,
 77,
 88,
 99,
 11,
 22,
 33,
 44,
 55,
 66,
 77,
 88,
 99,
 11,
 22,
 33,
 44,
 55,
 66,
 77,
 88,
 99]

In [5]:
import numpy as np
nparr = np.array(arr)
nparr

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [6]:
nparr+100


array([111, 122, 133, 144, 155, 166, 177, 188, 199])

In [7]:
nparr-9

array([ 2, 13, 24, 35, 46, 57, 68, 79, 90])

In [8]:
nparr*10

array([110, 220, 330, 440, 550, 660, 770, 880, 990])

In [9]:
nparr/10


array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

In [10]:
np.round(nparr/100,1)

array([0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9, 1. ])

In [11]:
print(nparr.max(), nparr.min(), nparr.sum(), nparr.mean())

99 11 495 55.0


In [17]:
##  Type of Values in Arrays

In [16]:
mArr  = np.array([11, 22, 33, 44, 67.89])
print(mArr)

[11.   22.   33.   44.   67.89]


In [18]:
print(mArr.shape)

(5,)


In [19]:
print(mArr.dtype)

float64


In [21]:
print(mArr.dtype)

float64


# Data Types for ndarrays

In [22]:
arr1 = np. array([1,2,3], dtype = np.float64)
arr2 = np. array([1,2,3], dtype = np.int32)

In [24]:
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [25]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [26]:
print(arr.dtype)

int64


In [27]:
float_arr = arr.astype(np.float64)
print(float_arr.dtype)


float64


#            Type        TypeCode

    int8          i1, u1         signed & unsigned 8-bit (1-byte) integer types)
    int16,uint16  i2, u2         signed & unsigned 16-bit (1-byte) integer types)
    int32,uint32  i4, u4         signed & unsigned 32-bit (1-byte) integer types)
    int64,uint64  i8, u8         signed & unsigned 64-bit (1-byte) integer types)    
    float64       f8,d           standard double-preision floating point
    bool          ?              Boolean type storing True & False value
    object        o              Python object type, a value can be any python object
    string_       S              Fixed length ASCII type ( 1 byte per character )
                                 e.g to creat a string dtype with length 10, use 'S10'
    unicode_      U              Fixed length Unicode type ( number of bytes platform specific)
                                 e.g to create a unicode dtype with length 10, user 'U10'

In [28]:
arr

array([1, 2, 3, 4, 5])

In [29]:
arr > 4

array([False, False, False, False,  True])

In [30]:
arr[arr>4] # returns a new value array with values satisfying the condition

array([5])

In [31]:
np.where(arr>3) # returns a new index value array with index value satisfying the condition

(array([3, 4]),)

In [32]:
type(np.where(arr>3))

tuple

In [33]:
type(arr[arr>4])

numpy.ndarray

# Slicing

In [34]:
letters = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])

In [35]:
letters[:]  #everything from array

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='<U1')

In [36]:
letters[::] # everything from array

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='<U1')

In [38]:
letters[2:] # START  2 STOP end of array STEP 1

array(['c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='<U1')

In [39]:
letters[:7] # START 0 STOP 7 STEP 1

array(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='<U1')

In [40]:
letters[-8: -3] # START -8 STOP -3 STEP 1

array(['c', 'd', 'e', 'f', 'g'], dtype='<U1')

In [41]:
letters[2:7] == letters[-8:-3]

array([ True,  True,  True,  True,  True])

In [42]:
letters[8:2] # START 8 STOP 2 STEP 1

array([], dtype='<U1')

In [43]:
letters[8:2:-1] # REVERSE  START 8 STOP 2 STEP -1

array(['i', 'h', 'g', 'f', 'e', 'd'], dtype='<U1')

In [44]:
letters[-3:-7:-1] 

array(['h', 'g', 'f', 'e'], dtype='<U1')

In [45]:
letters[-5:] # last 5 values in array

array(['f', 'g', 'h', 'i', 'j'], dtype='<U1')

In [46]:
# everything excpet last index value
letters[0:-1]

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='<U1')

In [47]:
letters[:-1]

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='<U1')

In [48]:
letters[:-2] # everything except last 2 index value


array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], dtype='<U1')

In [49]:
# every 3rd element in the array 
letters[::3]

array(['a', 'd', 'g', 'j'], dtype='<U1')

In [51]:
# every 3rd element in the arry a backward
letters[::-3]

array(['j', 'g', 'd', 'a'], dtype='<U1')

# Multiple Array Operations

In [53]:
a1 = np.arange(20)
a2 = np.arange(10)

print(a1)
print(a2)
print(a1.shape == a2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6 7 8 9]
False


In [54]:
a1 + a2


ValueError: operands could not be broadcast together with shapes (20,) (10,) 

In [58]:
a1[0:10]+a2


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# Assignemnet : : Finance data Analysis

In [59]:
# input data
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]

expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [63]:
print(type(revenue))
print(type(expenses))

<class 'list'>
<class 'list'>


In [64]:
revenue = np.array(revenue)
expenses = np.array(expenses)

In [65]:
print(type(revenue))
print(type(expenses))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [70]:
# we need to calcualate monthly profit for all months
monthly_profit = revenue-expenses
monthly_profit

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [76]:
# Calculate Profit after Tax (PAT), tax amount 30% on monthly profit, for all months
PAT = monthly_profit*0.7
PAT

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [67]:
# Profit Margin, PAT divided by revenue, calculate as percentage with 0 decimals
# and represents as int datatype

In [68]:
# Get Boolean array for best month
# Best month is where PAT is more than average of all months PAT

In [ ]:
# Get Boolen array for worst month
# Worst month is where PAT is less than average of all months PAT