In [2]:
import numpy as np

In [3]:
# 1d array
# a = [ 1, 2, 3, 4]
# a.ndim  1
# a.shape (4, )

# 2d array / matrix
# b = [[0,1], [1,2], [2, 3]]
# b.ndim  2
# b.shape (3, 2)



In [5]:
m2 = np.array([[0,4,8,12],[16,1,5,9],[10,14,18,3],[7,11,15,19]])
m2

array([[ 0,  4,  8, 12],
       [16,  1,  5,  9],
       [10, 14, 18,  3],
       [ 7, 11, 15, 19]])

In [19]:
m3 = np.array([[0,4,8,12],[16,1,5,9],[10,14,18,3],[7,11,15,19]])
m3

array([[ 0,  4,  8, 12],
       [16,  1,  5,  9],
       [10, 14, 18,  3],
       [ 7, 11, 15, 19]])

In [10]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [12]:
# reshape the matrix newshape = row x col
m1 = np.reshape( arr, (3,2))
m1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [13]:
# Matrix with Zeros
zarr = np.zeros((3,6))
zarr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
# Empty Matrix
earr = np.empty((3,6))
earr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
# Random Matrix - normally distributed values
rarr = np.random.randn(6,3)
rarr

array([[ 0.11907988, -0.19748542, -0.20218358],
       [-1.17588866, -0.63569936, -1.24363751],
       [-0.46168094, -1.505672  , -1.73068941],
       [-1.57455507,  1.96482632,  0.29505887],
       [ 0.34430517,  0.30646989,  1.12852663],
       [ 1.07725223, -1.78191484, -1.19608029]])

In [20]:
# transpose
rarr.T


array([[ 0.11907988, -1.17588866, -0.46168094, -1.57455507,  0.34430517,
         1.07725223],
       [-0.19748542, -0.63569936, -1.505672  ,  1.96482632,  0.30646989,
        -1.78191484],
       [-0.20218358, -1.24363751, -1.73068941,  0.29505887,  1.12852663,
        -1.19608029]])

In [23]:
arr = np.arange(15).reshape(5,3).T
arr

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [24]:
m1.shape


(3, 2)

In [25]:
m2.shape


(4, 4)

In [28]:
m1 = np.arange(20).reshape(5,4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

m1[::2,::2]

In [29]:
m1[0:2, 1]

array([1, 5])

In [30]:
Pdict = {"David":0,"Joe":1,"James":2,"Anthony":3,"Danny":4,"Chris":5,"Paul":6,"Kevin":7,"Derrick":8,"Dwayne":9}



In [32]:
obj3 = pd.Series(Pdict)
obj3

NameError: name 'pd' is not defined